#!/usr/bin/env bash
# create_shortcut.sh  —  Mac only
# Creates a TradingAgents double-clickable icon on the Desktop.
# Run once: ./create_shortcut.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DESKTOP="$HOME/Desktop"
COMMAND_FILE="$DESKTOP/TradingAgents.command"

cat > "$COMMAND_FILE" << HEREDOC
#!/bin/bash
# TradingAgents launcher — generated by create_shortcut.sh
cd "$SCRIPT_DIR"
./run_safe.sh
HEREDOC

chmod +x "$COMMAND_FILE"

echo "Shortcut created : $COMMAND_FILE"
echo "Double-click TradingAgents on your Desktop to open Terminal and launch."
echo ""
echo "Tip: to give it a custom icon, right-click the file in Finder"
echo "     → Get Info → drag a .icns image onto the icon in the top-left."
